# Generated by Django 2.1.1 on 2018-10-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='昵称')),
                ('Gender', models.CharField(max_length=10, verbose_name='性别')),
                ('Nation', models.CharField(max_length=30, verbose_name='国籍')),
                ('Motto', models.TextField(verbose_name='个人签名')),
                ('AC_num', models.IntegerField(default=0, verbose_name='通过题数')),
                ('Submit_num', models.IntegerField(default=0, verbose_name='提交题数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
