# Generated by Django 2.1.1 on 2018-10-13 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=25)),
                ('Reg_Email', models.TextField()),
                ('Reg_Time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=5, null=True)),
                ('Nation', models.CharField(max_length=15, null=True)),
                ('Motto', models.TextField(null=True)),
                ('Submit_num', models.IntegerField()),
                ('Ac_num', models.IntegerField()),
                ('Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Users')),
            ],
        ),
    ]
