# Generated by Django 2.1 on 2018-10-15 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Nation', models.CharField(max_length=30)),
                ('Motto', models.TextField()),
                ('AC_num', models.IntegerField(default=0)),
                ('Submit_num', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='昵称')),
            ],
        ),
    ]
