# Generated by Django 2.1.1 on 2018-10-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0003_motto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motto',
            old_name='author',
            new_name='mottoauthor',
        ),
    ]
