# Generated by Django 2.1.1 on 2018-10-13 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0004_auto_20181013_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
