# Generated by Django 2.1.1 on 2018-10-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0007_auto_20181013_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
