# Generated by Django 2.1.1 on 2018-10-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0008_new_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='motto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
