# Generated by Django 2.1.1 on 2018-10-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0009_motto_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='1', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='new',
            name='newstype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='oj_base.newsType'),
            preserve_default=False,
        ),
    ]
