# Generated by Django 2.1.1 on 2018-10-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0010_auto_20181013_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='type_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
