# Generated by Django 2.1.1 on 2018-10-13 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0011_auto_20181013_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='new',
            name='newstype',
            field=models.ForeignKey(default='通知', on_delete=django.db.models.deletion.DO_NOTHING, to='oj_base.newsType'),
        ),
        migrations.AlterField(
            model_name='newstype',
            name='type_name',
            field=models.CharField(default='暂无标签', max_length=20),
        ),
    ]
