# Generated by Django 2.1.1 on 2018-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj_base', '0012_auto_20181013_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstype',
            name='type_name',
            field=models.CharField(max_length=20),
        ),
    ]
